name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    eslint:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install modules
          run: yarn install

        - name: Run ESLint
          run: yarn eslint --max-warnings=0

        - name: Run Stylelint
          run: yarn stylelint --max-warnings=0

        - name: Build
          run: yarn build
